In [2]:
pip install pandas scikit-learn xgboost

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('IMDB Dataset.csv')
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [5]:
missing_values = data.isna().sum()
missing_values

review       0
sentiment    0
dtype: int64

In [6]:
x = data.iloc[:,0:1].values
x

array([["One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due t

In [7]:
y = data.iloc[:,1].values
y

array(['positive', 'positive', 'positive', ..., 'negative', 'negative',
       'negative'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
x_test 

array([['John Cassavetes is on the run from the law. He is at the bottom of the heap. He sees Negro Sidney Poitier as his equal and they quickly become friends, forming a sort of alliance against a bully of a foreman played by Jack Warden.<br /><br />As someone who has worked in a warehouse myself when I was younger, I can tell you that the warehouse fights, complete with tumbling packing cases and flailing grappling hooks are as realistic as it gets. I\'ve been in fights like these myself, although no one got killed.<br /><br />The introduction of Sidney Poitier\'s widow is a variation on Shakespeare\'s Shylock "Do I not bleed?" This is an anti racist film, which, at the time, was much needed.<br /><br />All the three principle characters - Warden, Cassavetes and Poitier - are superb, with Warden the most outstanding of the three.'],
       ['It\'s not just that the movie is lame. It\'s more than that. This movie is just unnecessary. Do we need another Western? How about a western wit

In [13]:
y_test

array([1, 0, 0, ..., 1, 1, 0])

In [14]:
x_train = x_train.tolist()
x_test = x_test.tolist()

In [15]:
x_train = [str(review).lower() for review in x_train]
x_test = [str(review).lower() for review in x_test]

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tf = TfidfVectorizer(max_features=5000)
x_train = tf.fit_transform(x_train)
x_test = tf.transform(x_test)
x_train

<40000x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 4685222 stored elements in Compressed Sparse Row format>

In [18]:
x_test

<10000x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 1178174 stored elements in Compressed Sparse Row format>

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
mnb = MultinomialNB()
model = mnb.fit(x_train,y_train)
y_prediction = model.predict(x_test)
y_prediction

array([1, 0, 1, ..., 1, 1, 0])

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
print("naive bayes accuracy score =",accuracy_score(y_test, y_prediction))

naive bayes accuracy score = 0.8477


In [23]:
from sklearn.metrics import classification_report

In [24]:
print("naive bayes Classification Report:",classification_report(y_test, y_prediction))

naive bayes Classification Report:               precision    recall  f1-score   support

           0       0.85      0.85      0.85      5035
           1       0.85      0.85      0.85      4965

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000



In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rfc = RandomForestClassifier()
model1 = rfc.fit(x_train,y_train)
y_prediction2 = model1.predict(x_test)
y_prediction2

array([1, 0, 1, ..., 1, 0, 0])

In [27]:
print("Random Forest Classifier accuracy score =",accuracy_score(y_test, y_prediction2))

Random Forest Classifier accuracy score = 0.839


In [28]:
print("Random Forest Classification Report:",classification_report(y_test, y_prediction2))

Random Forest Classification Report:               precision    recall  f1-score   support

           0       0.84      0.85      0.84      5035
           1       0.84      0.83      0.84      4965

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000



In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
knn = KNeighborsClassifier()
model2 = knn.fit(x_train,y_train)
y_prediction3 = model2.predict(x_test)
y_prediction3

array([1, 0, 1, ..., 1, 0, 0])

In [31]:
print("knn accuracy score =",accuracy_score(y_test, y_prediction3))

knn accuracy score = 0.7214


In [32]:
print("knn Classification Report:",classification_report(y_test, y_prediction3))

knn Classification Report:               precision    recall  f1-score   support

           0       0.75      0.68      0.71      5035
           1       0.70      0.77      0.73      4965

    accuracy                           0.72     10000
   macro avg       0.72      0.72      0.72     10000
weighted avg       0.72      0.72      0.72     10000



In [33]:
from xgboost import XGBClassifier

In [34]:
xgb = XGBClassifier()
model3 = xgb.fit(x_train,y_train)
y_prediction4 = model3.predict(x_test)
y_prediction4

array([1, 0, 1, ..., 1, 0, 0])

In [35]:
print("xgboosting accuracy score =",accuracy_score(y_test, y_prediction4))

xgboosting accuracy score = 0.8571


In [36]:
print("xgboosting Classification Report:",classification_report(y_test, y_prediction4))

xgboosting Classification Report:               precision    recall  f1-score   support

           0       0.87      0.84      0.86      5035
           1       0.84      0.87      0.86      4965

    accuracy                           0.86     10000
   macro avg       0.86      0.86      0.86     10000
weighted avg       0.86      0.86      0.86     10000



In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
lr = LogisticRegression()
model4 = lr.fit(x_train,y_train)
y_prediction5 = model4.predict(x_test)
y_prediction5

array([1, 0, 1, ..., 1, 0, 0])

In [39]:
print("Logistic Regression accuracy score =",accuracy_score(y_test, y_prediction5))

Logistic Regression accuracy score = 0.887


In [40]:
print("Logistic Regression Classification Report:",classification_report(y_test, y_prediction5))

Logistic Regression Classification Report:               precision    recall  f1-score   support

           0       0.90      0.88      0.89      5035
           1       0.88      0.90      0.89      4965

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



In [41]:
from sklearn.tree import DecisionTreeClassifier

In [42]:
dtc = DecisionTreeClassifier()
model5 = dtc.fit(x_train,y_train)
y_prediction6 = model5.predict(x_test)
y_prediction6

array([0, 0, 0, ..., 1, 0, 0])

In [43]:
print("Descision Tree Classifier accuracy score =",accuracy_score(y_test, y_prediction6))

Descision Tree Classifier accuracy score = 0.7195


In [44]:
print("Descision Tree Classification Report:",classification_report(y_test, y_prediction6))

Descision Tree Classification Report:               precision    recall  f1-score   support

           0       0.72      0.72      0.72      5035
           1       0.72      0.72      0.72      4965

    accuracy                           0.72     10000
   macro avg       0.72      0.72      0.72     10000
weighted avg       0.72      0.72      0.72     10000

